server:
   port: 5000
spring:
   datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://magneto.cihdpvf9suth.us-east-2.rds.amazonaws.com:3306/magneto?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: Nidia0619
api:
   database:
      sp:
        consult: CALL magneto.sp_select_dna_testing_record()
        insert: CALL magneto.sp_insert_dna_testing_record(:dna,:isMutan)
   constants:
        dnaLetters: ATCG
        dnaSize: 6
        notMutant: Es humano no mutante.
        validate: El ADN ingresado no cumple con las validaciones pertinentes.
        errorExceptionService: Error al consumir el servicio api. Por favor comunicarse con el administrador.